import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
 
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className=''>
       <div className="w-1/12 h-full bg-red-600">
        <div className='bg-black w-full h-14'></div>
        <div className='bg-black w-full h-14'></div>
        <div className='bg-black w-full h-14'></div>
        <div className='bg-black w-full h-14'></div>
        <div className='bg-black w-full h-14'></div>
        <div className='bg-black w-full h-14'></div>
        <div className='bg-black w-full h-14'></div>
        <div className='bg-black w-full h-14'></div>
        <div className='bg-black w-full h-14'></div>
        <div className='bg-black w-full h-14'></div>
        <div className='bg-black w-full h-14'></div>
        <div className='bg-black w-full h-14'></div>
        <div className='bg-black w-full h-14'></div>
        <div className='bg-black w-full h-14'></div>
        <div className='bg-black w-full h-14'></div>
        <div className='bg-black w-full h-14'></div>
        <div className='bg-black w-full h-14'></div>
        <div className='bg-black w-full h-14'></div>
        <div className='bg-black w-full h-14'></div>
        <div className='bg-black w-full h-14'></div>
        <div className='bg-black w-full h-14'></div>
        

       </div>
        {children}
           
        
    </div>
  )
}
